# Generated by Django 3.2.6 on 2021-09-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(max_length=200),
        ),
    ]
