# Generated by Django 3.2.6 on 2021-09-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_tasktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskComplete',
            field=models.BooleanField(default=False),
        ),
    ]
